##############################################
# generic ansible config information
##############################################
ansible_user: "devops"
bootstrap_user: "devops"
initial_remote_user: "root"

github_user_pubkeys:
  - parithosh
  - holgerd77
  - jochem-brouwer
  - alcuadrado

ansible_python_interpreter: /usr/bin/python3
oh_my_zsh_config:
  PROMPT: "%{$fg[yellow]%}%n%{$fg[white]%}@%{$fg[red]%}%m%{$reset_color%} ${PROMPT}"

##############################################
# el endpoints
##############################################
# nimbus requires a websocket endpoint (http support unstable)
# note: also used for execution engine endpoint in nimbus
consensus_endpoint_nimbus: ws://127.0.0.1:8551
beacon_api_endpoint: "http://127.0.0.1:{{beacon_api_port}}"
elendpoint: http://127.0.0.1:8545

# Merge Engine endpoints
# TODO change IP?
# TODO: some engines might start using the 8550 port (or 8551 for ws)

##############################################
# testnet specific information
##############################################
testnet_type: custom
cl_network_name: shandong-testnet
chainID: 1337902
terminal_total_difficulty: "0"
fee_recipient: "0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134"
# enter bootnodes here if needed
bootnode_enrs:
  - "enr:-LK4QKKhUEqpRqbQQgwWjEk0WOH9F7HUS5JEcgCBIcKVDpHTCjxmyoGL-iqQgqxu9lKKAfwGiOWrYe49OilEY7sJx7IGh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD992pNITN5Av__________gmlkgnY0gmlwhC5lfi2Jc2VjcDI1NmsxoQONfH4lcqzKVlJbglBz7VVzW07NoPhEnOL5D_AgwDCMwoN0Y3CCIyiDdWRwgiMo"
  - "enr:-LK4QHaC8puKfbjSjDGB7R-Xy-SbeaQCDnONtY63fQIqB0b6QOhsqRq_E620EopW4JdESFYK_F-2lnaCVAJfKnSqEQ0Gh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD992pNITN5Av__________gmlkgnY0gmlwhLKAzkyJc2VjcDI1NmsxoQPRj9GgNiW00hvKYkANqSnGbXUn8soMN9vSonCKj8Rj44N0Y3CCIyiDdWRwgiMo"
  - "enr:-LK4QBMhnMsk0MZmV6IHYdN01mPZabPzQnmp_OTCROuke2tOebG-zEdMkG9acFY-_j_t220ZxG1VYM6vcLCI2ZHheAEGh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD992pNITN5Av__________gmlkgnY0gmlwhI5doAeJc2VjcDI1NmsxoQPaOh0F7sq3ODvFQvsHRYH61nSw6u0G0dNcmg-8qWGjBIN0Y3CCIyiDdWRwgiMo"
  - "enr:-LK4QOmFLTmNu1Yfexw-zS-ELU3Hy-mrfA7DdH2FW96qvNeqWXynlwyx80q6a13xsr6EZky6fN4Yda6yTo-O2cHlU_MGh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD992pNITN5Av__________gmlkgnY0gmlwhGj4FQSJc2VjcDI1NmsxoQOVRfcGuBmZWvxxJdjjLDGx1X9XP71ENeJ7bN0Ag0kybIN0Y3CCIyiDdWRwgiMo"
  - "enr:-LK4QHa5b9jGpbwVshdAFRLdcy427nEZGbNMW1JPxGfPVzw1MQ303N64Q2Mw3Vyrl0vIcV8X3Hv3KJ8-AqU9zwd4DqkGh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD992pNITN5Av__________gmlkgnY0gmlwhGj4-xSJc2VjcDI1NmsxoQIeuyfooRju47hdWUPd-nYK6PtCw5_aypZWV538Lb0eLIN0Y3CCIyiDdWRwgiMo"
  - "enr:-LK4QHXiiEV2er68JpBw6_1YNCdUuEap88JI8Br8TJrqpCZ5NFGehpb_MfbiU1STlo9VV75BWYBV-GxKK-QjM5mQEbQGh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD992pNITN5Av__________gmlkgnY0gmlwhKRcrjiJc2VjcDI1NmsxoQNdVnveQKw0_qEgiSUQJlOTlvnUZNby41M9oTdrOxP0w4N0Y3CCIyiDdWRwgiMo"
  - "enr:-LK4QBh2q8uQYyAXBPCotAi4IKd8ns0MPaszGeFgsuv3P-1sDuhfFyq2Pu1yjBo7Z_pAIT3FtlCMH2hZoFjpMSdZLuAGh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD992pNITN5Av__________gmlkgnY0gmlwhI5draqJc2VjcDI1NmsxoQJmAkK0EUFViT2srvC-LepxsGRFFu-Cl8yAvn0Q3saRd4N0Y3CCIyiDdWRwgiMo"
  - "enr:-LK4QNfk8mwUQz3ob4WIgwQonpEd099d9eTEUo7zzIocz_eSDOiDrRXXN2_-RiislzLeDuPDth2q3EzecLDgluf5-38Gh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD992pNITN5Av__________gmlkgnY0gmlwhLKAy_OJc2VjcDI1NmsxoQMMy7_kpdK316yY6ibqamMagXe0yF81yLTuyqBOeXHnqYN0Y3CCIyiDdWRwgiMo"
el_bootnode_enode:
  - "enode://11e43515d6258ab2bd814b25a50c911c155a46a27e9be8ce6ea68e293ec13aa4cd6740418baf9abf1e79ba9252c497d66aa4a293c94ef8168d0e7c211ef73690@46.101.126.45:30303"
  - "enode://95b683a66aba396551bafff688644fc6dc1bada2de78491f89b268ebdcf3d88dfc9942a9f2833ecc3887d49dfb4e96851c2f5eb0adde41847cc356f15ac4ac67@178.128.206.76:30303"
  - "enode://bcd3eeabca8ff3a1c3b19384e064cc79fda547939324e0699d030041a8960a1d68f1e19141d19305e79675be50434521d024352a5eae00da8ace7933abf20fdf@142.93.160.7:30303"
  - "enode://6a65c7e62360e1fcc98c88cf8dd8e9492d2e95372f5d7b742b73ab8f82e849bae196bd18b79bc9502b204cef7bf64b589147700368d877c32a76f9c4fd7dd941@104.248.21.4:30303"
  - "enode://2ae5ef4b4c338e4ee15a347aba8e60bcb451ca19d26f8d67e731bb5f2972ad6ce867ec85f9942a5efe349470106b21c49a9aeb5b00b91063e35f1c1643c0930c@104.248.251.20:30303"
  - "enode://85ecd8fcab723a33ee68e5f8530c9d264bd601899dc74af7f020bc2f8e0d0ad8ec5c5324364f127c77ddab607bc16e1c5fbae2c675b6d94a79a24222e7e4766e@164.92.174.56:30303"
  - "enode://24951d3b76f20aed18e32096941d572b98518c9e4dace6b7d0b1f34292dfc5ee7d295453b955be4d2967c6ce1948c11513cd70d76dbee8d3034ddb40d63f5517@142.93.173.170:30303"
  - "enode://73e2396ac78c462287edd22957096890ca1995a4995c51a1fe24accbe931209fb0fc5359fc1043a0edad3fc53ba64fba5262255c70a03e5fca86f924c261ad4f@178.128.203.243:30303"
  
##############################################
# metric information
##############################################
# enter pushgateway config if needed
prometheus_config_file: "prometheus/prometheus.yml.j2"
push_url: "https://example.test/insert/0/prometheus/api/v1/write"
push_metrics_enabled: false
remote_write_auth: false
eth_metrics_exporter_enabled: false
cl_validator_metrics_enabled: false
eth_metrics_exporter_name: "metrics-exporter"
eth_metrics_exporter_image: "samcm/ethereum-metrics-exporter:0.17.0"
remote_write_username: "test"
remote_write_password: "test"

no_validator_keys: false
ethstats_url: "example.io"
ethstats_password: "example"

##############################################
# mev boost configs
##############################################
mev_boost_image_name: flashbots/mev-boost:v0.8.2
mev_boost_container_name: mev_boost
mev_boost_start_args: "-genesis-fork-version 0x00 -relays http://example.io"
mev_boost: false

##############################################
# ports to configure
##############################################
el_rpc_port: 8545
el_ws_rpc_port: 8546
el_engine_port_no_auth: 8550
el_engine_port: 8551
el_engine_snoop_port: 8560
el_engine_ws_port: 8552
nimbus_rpc_port: 4009
beacon_api_port: 4000
beacon_grpc_port: 4001
beacon_metrics_port: 8000
beacon_p2p_port: 9000
validator_metrics_port: 8001
validator_rpc_port: 4002
node_exporter_web_listen_address: "127.0.0.1:9100"
prometheus_web_listen_address: "127.0.0.1:9101"
el_metrics_port: 8002
eth_metrics_exporter_port: 8003
mev_boost_port: 18550

##############################################
# Command for JSON RPC snooper
##############################################
snoop_image_name: parithoshj/json_rpc_snoop:v1.0.0-x86
snoop_container_name: snooper

##############################################
# name of the validator to display
##############################################
graffiti: "{{cl_client_name}}-{{el_client_name}}"

##############################################
# local data directories
##############################################
local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
local_custom_config_data_host_dir: "{{inventory_dir}}/../custom_config_data"
local_custom_config_data_host_archive: "{{inventory_dir}}/../custom_config_data.tar.gz"
local_cl_config_filepath: "{{local_custom_config_data_host_dir}}/config.yaml"
# private dirs
# Validator assignments
local_validator_host_dir: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}"
local_validator_host_archive: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}.tar.gz"

##############################################
# remote host data directories
##############################################
beacon_node_dir: "{{home_dir}}/beacon"
validator_node_dir: "{{home_dir}}/validator"
testnet_dir: "{{home_dir}}/custom_config_data"
el_node_dir: "{{home_dir}}/eldata"

##############################################
# common log config
##############################################
beacon_log_level: info
common_log_options:
  max-file: "10"
  max-size: 500m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file

##############################################
# container names
##############################################
beacon_container_name: beacon
validator_container_name: validator
execution_container_name: execution
hi_peer_count: 25
separate_validator_process_enabled: true

firewall_allowed_tcp_ports:
  - 22
  - 30303
  - 9000
  - 80
  - 443

firewall_allowed_udp_ports:
  - 30303
  - 9000

firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 8545 -s 46.101.126.45 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 8546 -s 46.101.126.45 -j ACCEPT"